require('./game-test.js');
require('./quick-enemy-test.js');
require('./flash-tower-test.js');
require('./simple-enemy-test.js');
require('./board-test.js');
require('./path-tile-test.js');
require('./tile-test.js');
require('./build-tile-test.js');
require('./simple-tower-test.js');
