var boardFiveOptions = {
  16: {type: 'path', isTurn: false},
  17: {type: 'path', isTurn: false},
  18: {type: 'path', isTurn: false},
  19: {type: 'path', isTurn: false},
  20: {type: 'path', isTurn: false},
  21: {type: 'path', isTurn: false},
  22: {type: 'path', isTurn: false},
  23: {type: 'path', isTurn: false},
  24: {type: 'path', isTurn: false},
  25: {type: 'path', isTurn: false},
  26: {type: 'path', isTurn: false},
  27: {type: 'path', isTurn: false},
  28: {type: 'path', isTurn: false},
  29: {type: 'path', isTurn: false},
  30: {type: 'path', isTurn: true, direction: 'down'},
  46: {type: 'path', isTurn: false},
  62: {type: 'path', isTurn: true, direction: 'left'},
  61: {type: 'path', isTurn: false},
  60: {type: 'path', isTurn: true, direction: 'down'},
  76: {type: 'path', isTurn: false},
  92: {type: 'path', isTurn: true, direction: 'left'},
  91: {type: 'path', isTurn: false},
  90: {type: 'path', isTurn: true, direction: 'up'},
  74: {type: 'path', isTurn: false},
  58: {type: 'path', isTurn: true, direction: 'left'},
  57: {type: 'path', isTurn: false},
  56: {type: 'path', isTurn: true, direction: 'down'},
  72: {type: 'path', isTurn: false},
  88: {type: 'path', isTurn: true, direction: 'left'},
  87: {type: 'path', isTurn: false},
  86: {type: 'path', isTurn: true, direction: 'up'},
  70: {type: 'path', isTurn: false},
  54: {type: 'path', isTurn: true, direction: 'left'},
  53: {type: 'path', isTurn: false},
  52: {type: 'path', isTurn: true, direction: 'down'},
  68: {type: 'path', isTurn: false},
  84: {type: 'path', isTurn: true, direction: 'left'},
  83: {type: 'path', isTurn: false},
  82: {type: 'path', isTurn: true, direction: 'down'},
  98: {type: 'path', isTurn: false},
  114: {type: 'path', isTurn: true, direction: 'right'},
  115: {type: 'path', isTurn: true, direction: 'down'},
  131: {type: 'path', isTurn: false},
  147: {type: 'path', isTurn: true, direction: 'right'},
  148: {type: 'path', isTurn: false},
  149: {type: 'path', isTurn: true, direction: 'up'},
  133: {type: 'path', isTurn: false},
  117: {type: 'path', isTurn: true, direction: 'right'},
  118: {type: 'path', isTurn: false},
  119: {type: 'path', isTurn: true, direction: 'down'},
  135: {type: 'path', isTurn: false},
  151: {type: 'path', isTurn: true, direction: 'right'},
  152: {type: 'path', isTurn: false},
  153: {type: 'path', isTurn: true, direction: 'up'},
  137: {type: 'path', isTurn: false},
  121: {type: 'path', isTurn: true, direction: 'right'},
  122: {type: 'path', isTurn: false},
  123: {type: 'path', isTurn: true, direction: 'down'},
  139: {type: 'path', isTurn: false},
  155: {type: 'path', isTurn: true, direction: 'right'},
  156: {type: 'path', isTurn: false},
  157: {type: 'path', isTurn: true, direction: 'up'},
  141: {type: 'path', isTurn: false},
  125: {type: 'path', isTurn: true, direction: 'right'},
  126: {type: 'path', isTurn: true, direction: 'up'},
  110: {type: 'path', isTurn: false},
  94: {type: 'path', isTurn: true, direction: 'right'},
  95: {type: 'path', isTurn: false},
  2: {type: 'build'},
  11: {type: 'build'},
  39: {type: 'build'},
  47: {type: 'build'},
  65: {type: 'build'},
  105: {type: 'build'},
  93: {type: 'build'},
  150: {type: 'build'}
};

module.exports = boardFiveOptions;
