var boardFourOptions = {
  128: {type: 'path', isTurn: false},
  129: {type: 'path', isTurn: false},
  130: {type: 'path', isTurn: false},
  131: {type: 'path', isTurn: false},
  132: {type: 'path', isTurn: false},
  133: {type: 'path', isTurn: false},
  134: {type: 'path', isTurn: true, direction: 'up'},
  118: {type: 'path', isTurn: false},
  102: {type: 'path', isTurn: false},
  86: {type: 'path', isTurn: false},
  70: {type: 'path', isTurn: false},
  54: {type: 'path', isTurn: false},
  38: {type: 'path', isTurn: false},
  22: {type: 'path', isTurn: false},
  6: {type: 'path', isTurn: true, direction: 'left'},
  5: {type: 'path', isTurn: false},
  4: {type: 'path', isTurn: false},
  3: {type: 'path', isTurn: false},
  2: {type: 'path', isTurn: false},
  1: {type: 'path', isTurn: false},
  0: {type: 'path', isTurn: true, direction: 'down'},
  16: {type: 'path', isTurn: false},
  32: {type: 'path', isTurn: false},
  48: {type: 'path', isTurn: false},
  64: {type: 'path', isTurn: false},
  80: {type: 'path', isTurn: false},
  96: {type: 'path', isTurn: true, direction: 'right'},
  97: {type: 'path', isTurn: false},
  98: {type: 'path', isTurn: false},
  99: {type: 'path', isTurn: false},
  100: {type: 'path', isTurn: true, direction: 'up'},
  84: {type: 'path', isTurn: false},
  68: {type: 'path', isTurn: false},
  52: {type: 'path', isTurn: false},
  36: {type: 'path', isTurn: true, direction: 'left'},
  35: {type: 'path', isTurn: false},
  34: {type: 'path', isTurn: true, direction: 'down'},
  50: {type: 'path', isTurn: false},
  66: {type: 'path', isTurn: true, direction: 'right'},
  67: {type: 'path', isTurn: false},
  69: {type: 'path', isTurn: false},
  71: {type: 'path', isTurn: false},
  72: {type: 'path', isTurn: false},
  73: {type: 'path', isTurn: false},
  74: {type: 'path', isTurn: false},
  75: {type: 'path', isTurn: false},
  76: {type: 'path', isTurn: false},
  77: {type: 'path', isTurn: true, direction: 'up'},
  61: {type: 'path', isTurn: false},
  45: {type: 'path', isTurn: true, direction: 'left'},
  44: {type: 'path', isTurn: false},
  43: {type: 'path', isTurn: true, direction: 'down'},
  59: {type: 'path', isTurn: false},
  91: {type: 'path', isTurn: false},
  107: {type: 'path', isTurn: true, direction: 'right'},
  108: {type: 'path', isTurn: false},
  109: {type: 'path', isTurn: false},
  110: {type: 'path', isTurn: false},
  111: {type: 'path', isTurn: true, direction: 'up'},
  95: {type: 'path', isTurn: false},
  79: {type: 'path', isTurn: false},
  63: {type: 'path', isTurn: false},
  47: {type: 'path', isTurn: false},
  31: {type: 'path', isTurn: false},
  15: {type: 'path', isTurn: true, direction: 'left'},
  14: {type: 'path', isTurn: false},
  13: {type: 'path', isTurn: false},
  12: {type: 'path', isTurn: false},
  11: {type: 'path', isTurn: false},
  10: {type: 'path', isTurn: false},
  9: {type: 'path', isTurn: true, direction: 'down'},
  25: {type: 'path', isTurn: false},
  41: {type: 'path', isTurn: false},
  57: {type: 'path', isTurn: false},
  89: {type: 'path', isTurn: false},
  105: {type: 'path', isTurn: false},
  121: {type: 'path', isTurn: false},
  137: {type: 'path', isTurn: true, direction: 'right'},
  138: {type: 'path', isTurn: false},
  139: {type: 'path', isTurn: false},
  140: {type: 'path', isTurn: false},
  141: {type: 'path', isTurn: false},
  142: {type: 'path', isTurn: false},
  143: {type: 'path', isTurn: false},
  112: {type: 'build'},
  101: {type: 'build'},
  17: {type: 'build'},
  56: {type: 'build'},
  122: {type: 'build'},
  28: {type: 'build'},
  94: {type: 'build'},
  158: {type: 'build'},
};

module.exports = boardFourOptions;
