var boardTwoOptions = {
  16: {type: 'path', isTurn: false},
  17: {type: 'path', isTurn: false},
  18: {type: 'path', isTurn: false},
  19: {type: 'path', isTurn: false},
  20: {type: 'path', isTurn: true, direction: 'down'},
  36: {type: 'path', isTurn: false},
  52: {type: 'path', isTurn: false},
  68: {type: 'path', isTurn: false},
  84: {type: 'path', isTurn: false},
  100: {type: 'path', isTurn: false},
  116: {type: 'path', isTurn: true, direction: 'right'},
  117: {type: 'path', isTurn: false},
  118: {type: 'path', isTurn: false},
  119: {type: 'path', isTurn: true, direction: 'up'},
  103: {type: 'path', isTurn: false},
  87: {type: 'path', isTurn: false},
  71: {type: 'path', isTurn: true, direction: 'up'},
  72: {type: 'path', isTurn: false},
  73: {type: 'path', isTurn: false},
  74: {type: 'path', isTurn: false},
  75: {type: 'path', isTurn: true, direction: 'down'},
  91: {type: 'path', isTurn: false},
  107: {type: 'path', isTurn: false},
  123: {type: 'path', isTurn: true, direction: 'right'},
  124: {type: 'path', isTurn: false},
  125: {type: 'path', isTurn: false},
  126: {type: 'path', isTurn: true, direction: 'up'},
  110: {type: 'path', isTurn: false},
  94: {type: 'path', isTurn: false},
  78: {type: 'path', isTurn: false},
  62: {type: 'path', isTurn: false},
  46: {type: 'path', isTurn: true, direction: 'right'},
  47: {type: 'path', isTurn: false},
  2: {type: 'build'},
  115: {type: 'build'},
  69: {type: 'build'},
  86: {type: 'build'},
  135: {type: 'build'},
  41: {type: 'build'},
  105: {type: 'build'},
  76: {type: 'build'},
  157: {type: 'build'},
  13: {type: 'build'},
  95: {type: 'build'}
};

module.exports = boardTwoOptions;
